# Generated by Django 6.0 on 2025-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClimateTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trends_images/')),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research')),
                ('description', models.TextField()),
            ],
        ),
    ]
