# Generated by Django 6.0 on 2025-12-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateapp', '0003_rename_description_research_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatenews',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='climatenews',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='climatenews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='climatenews',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='climatenews',
            name='title',
        ),
        migrations.AddField(
            model_name='climatenews',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='climatenews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClimateTip',
        ),
    ]
